environment:
  domain: "labs.local"
  manager: "ceph-adm"
  base_box: "frjaraur/xenial64"
  base_box_version: "1.4"

boxes:
- name: "ceph-mon"
  ceph_role: "monitor"
  mgmt_ip: "10.10.10.9"
  hostonly_ip: "192.168.56.9"
  mem: "1524"
  cpu: "1"

- name: "ceph-osd1"
  ceph_role: "datanode"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1524"
  cpu: "1"
  
- name: "ceph-osd2"
  ceph_role: "datanode"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"
  
- name: "ceph-osd3"
  ceph_role: "datanode"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"
  
- name: "ceph-adm"
  ceph_role: "manager"
  mgmt_ip: "10.10.10.10"
  hostonly_ip: "192.168.56.10"
  mem: "1524"
  cpu: "1"

